# Generated by Django 4.2.13 on 2024-07-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify', '0002_rename_title_music_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='history',
            field=models.ManyToManyField(related_name='music_history', through='spotify.History', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(related_name='liked_music', to='spotify.musiclikes'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(related_name='playlist', to='spotify.music'),
        ),
        migrations.AlterField(
            model_name='history',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history_music', to='spotify.music'),
        ),
    ]
