# Generated by Django 4.2.13 on 2024-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_music_history_music_likes_playlist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liked_music', to='spotify.musiclikes'),
        ),
    ]
