# Generated by Django 4.2.13 on 2024-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_alter_music_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_music', to='spotify.musiclikes'),
        ),
    ]
