# Generated by Django 4.2.13 on 2024-07-17 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify', '0005_alter_music_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='music_history', through='spotify.History', to=settings.AUTH_USER_MODEL),
        ),
    ]
